package tasks;


/**
* tasks/AbstractTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 8:43:54 PM CEST
*/

public interface AbstractTask extends org.omg.CORBA.portable.IDLEntity
{
  String info ();
  tasks.AbstractTask next () throws tasks.TaskException;
} // interface AbstractTask
