package tasks;


/**
* tasks/AdderTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 8:43:54 PM CEST
*/

public interface AdderTaskOperations  extends tasks.AbstractTask
{
  int a ();
  float b ();
  double result ();
  void result (double newResult);
} // interface AdderTaskOperations
