package tasks;


/**
* tasks/FlipLineTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 9:02:28 PM CEST
*/

public interface FlipLineTaskOperations  extends tasks.AbstractTask
{
  void update (tasks.Point[] flippedPolyLine, org.omg.CORBA.IntHolder lengthDifference);
} // interface FlipLineTaskOperations
