package tasks;


/**
* tasks/Point.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 8:43:54 PM CEST
*/

public final class Point implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Point ()
  {
  } // ctor

  public Point (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Point
