package tasks;


/**
* tasks/SimpleTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 9:02:28 PM CEST
*/

public interface SimpleTask extends SimpleTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SimpleTask
