package tasks;


/**
* tasks/SimpleTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hw01.idl
* Friday, April 2, 2021 8:43:54 PM CEST
*/

public interface SimpleTaskOperations  extends tasks.AbstractTask
{
  boolean isReady ();
} // interface SimpleTaskOperations
